

ss_model.o : 
	@echo Counter bound :  $(MODEL_DEPTH) 
	@echo . 
	@echo . 
	@echo . 
	@echo . 
	
	$(CC) $(CC_OPTIONS) -I$(SRC_ROOT) -I. -D MAX=$(MODEL_DEPTH) -c ss_model.c -o $(PLUG_MODEL_BIN_DIR)/ss_model.o